
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.File;
import java.net.URL;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.HashSet;
import java.util.Set;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;


public class Addcategory extends javax.swing.JFrame
{

    String photofile = "";

    
    public Addcategory()
    {
        initComponents();
        setSize(500, 500);
        setVisible(true);
        
        setResizable(false);
        setTitle("Add Categories");
         int width=Toolkit.getDefaultToolkit().getScreenSize().width;
        int height=Toolkit.getDefaultToolkit().getScreenSize().height;
      int x=(width/2)-(this.getWidth()/2);
      int y=(height/2)-(this.getHeight()/2);
        setLocation(x, y);
        try {
            File f=new File(System.getProperty("user.home")+"\\images\\b.jpg");
            
                    Image scaledInstance = ImageIO.read(f).getScaledInstance(lb_background.getWidth(), lb_background.getHeight(),
                            Image.SCALE_SMOOTH);
                    lb_background.setIcon(new ImageIcon(scaledInstance));
        } catch (Exception e) {
        e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_cname = new javax.swing.JLabel();
        tf_cname = new javax.swing.JTextField();
        lb_category_desc = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_cdesc = new javax.swing.JTextArea();
        lb_category_photo = new javax.swing.JLabel();
        bt_browse = new javax.swing.JButton();
        lb_browse_image = new javax.swing.JLabel();
        bt_addcategory = new javax.swing.JButton();
        lb_background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        lb_cname.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        lb_cname.setForeground(new java.awt.Color(255, 255, 255));
        lb_cname.setText("Category Name");
        getContentPane().add(lb_cname);
        lb_cname.setBounds(20, 20, 120, 30);
        getContentPane().add(tf_cname);
        tf_cname.setBounds(210, 20, 150, 30);

        lb_category_desc.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        lb_category_desc.setForeground(new java.awt.Color(255, 255, 255));
        lb_category_desc.setText("Category Description");
        getContentPane().add(lb_category_desc);
        lb_category_desc.setBounds(20, 70, 160, 40);

        ta_cdesc.setColumns(20);
        ta_cdesc.setRows(5);
        jScrollPane1.setViewportView(ta_cdesc);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(210, 80, 166, 80);

        lb_category_photo.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        lb_category_photo.setForeground(new java.awt.Color(255, 255, 255));
        lb_category_photo.setText("Category Photo");
        getContentPane().add(lb_category_photo);
        lb_category_photo.setBounds(20, 190, 140, 30);

        bt_browse.setBackground(new java.awt.Color(0, 0, 0));
        bt_browse.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        bt_browse.setForeground(new java.awt.Color(255, 255, 255));
        bt_browse.setText("BROWSE");
        bt_browse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_browseActionPerformed(evt);
            }
        });
        getContentPane().add(bt_browse);
        bt_browse.setBounds(210, 200, 110, 40);
        getContentPane().add(lb_browse_image);
        lb_browse_image.setBounds(280, 200, 110, 80);

        bt_addcategory.setBackground(new java.awt.Color(0, 0, 0));
        bt_addcategory.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        bt_addcategory.setForeground(new java.awt.Color(255, 255, 255));
        bt_addcategory.setText("ADD");
        bt_addcategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_addcategoryActionPerformed(evt);
            }
        });
        getContentPane().add(bt_addcategory);
        bt_addcategory.setBounds(210, 300, 110, 40);

        lb_background.setText("jLabel1");
        getContentPane().add(lb_background);
        lb_background.setBounds(0, -6, 510, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_browseActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_bt_browseActionPerformed
    {//GEN-HEADEREND:event_bt_browseActionPerformed
        try
          {
            JFileChooser jf = new JFileChooser();
            int showOpenDialog = jf.showOpenDialog(this);

            if (showOpenDialog == JFileChooser.APPROVE_OPTION)
              {
                File f = jf.getSelectedFile();
                photofile = f.getPath();
                Image img = ImageIO.read(f);
                Image bimg = img.getScaledInstance(lb_browse_image.getWidth(), lb_browse_image.getHeight(), Image.SCALE_SMOOTH);
                ImageIcon imgic = new ImageIcon(bimg);
                lb_browse_image.setIcon(imgic);
              } else
              {
    File f=new File(System.getProperty("user.home")+"\\images\\dummy.jpg");
              photofile = f.getPath();
              }

          } catch (Exception e)
          {
            e.printStackTrace();
          }
    }//GEN-LAST:event_bt_browseActionPerformed

    private void bt_addcategoryActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_bt_addcategoryActionPerformed
    {//GEN-HEADEREND:event_bt_addcategoryActionPerformed
        String catname = tf_cname.getText();
        String catdesc = ta_cdesc.getText();
        if (catname.isEmpty() || catdesc.isEmpty())
          {
            JOptionPane.showMessageDialog(this, "Please provide required details");
          } else
          {
            try
              {
                Class.forName("com.mysql.jdbc.Driver");
                System.out.println("Driver Loading done");

                Connection conn = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/parkingbookingsystem", "root", "system");
                System.out.println("Connection Created");

                Statement stmt = conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,
                        ResultSet.CONCUR_UPDATABLE);
                System.out.println("Statement Created");

                ResultSet rs = stmt.executeQuery("select * from category where cname='" + catname + "'");
                System.out.println("ResultSet Created\n\n");
                if (rs.next())
                  {
                    JOptionPane.showMessageDialog(this, "Category already exists");

                  } else
                  {
                    if (photofile.equals(""))
                      {
       File f=new File(System.getProperty("user.home")+"\\images\\dummy.jpg");
              photofile = f.getPath();
                      }
                    rs.moveToInsertRow();
                    rs.updateString("cname", catname);
                    rs.updateString("cdescription", catdesc);
                    rs.updateString("cphoto", photofile);
                    rs.insertRow();
                    JOptionPane.showMessageDialog(this, "Added successfully");
                    tf_cname.setText("");
                    ta_cdesc.setText("");

                  }

              } catch (Exception e)
              {
                e.printStackTrace();
              }
          }
    }//GEN-LAST:event_bt_addcategoryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
          {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
              {
                if ("Nimbus".equals(info.getName()))
                  {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                  }
              }
          } catch (ClassNotFoundException ex)
          {
            java.util.logging.Logger.getLogger(Addcategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (InstantiationException ex)
          {
            java.util.logging.Logger.getLogger(Addcategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (IllegalAccessException ex)
          {
            java.util.logging.Logger.getLogger(Addcategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (javax.swing.UnsupportedLookAndFeelException ex)
          {
            java.util.logging.Logger.getLogger(Addcategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                //new Addcategory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_addcategory;
    private javax.swing.JButton bt_browse;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_background;
    private javax.swing.JLabel lb_browse_image;
    private javax.swing.JLabel lb_category_desc;
    private javax.swing.JLabel lb_category_photo;
    private javax.swing.JLabel lb_cname;
    private javax.swing.JTextArea ta_cdesc;
    private javax.swing.JTextField tf_cname;
    // End of variables declaration//GEN-END:variables
}
