
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.net.URL;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


public class Admin_Change_Password extends javax.swing.JFrame
{

    String email;
    public Admin_Change_Password(String email)
    {
        initComponents();
         setSize(500,500);
        setVisible(true);
         setTitle("Admin Change Password");
        setResizable(false);
         int width=Toolkit.getDefaultToolkit().getScreenSize().width;
        int height=Toolkit.getDefaultToolkit().getScreenSize().height;
      int x=(width/2)-(this.getWidth()/2);
      int y=(height/2)-(this.getHeight()/2);
        setLocation(x, y);
        this.email=email;
        try {
             File f=new File(System.getProperty("user.home")+"\\images\\c.jpg");
                    Image scaledInstance = ImageIO.read(f).getScaledInstance(lb_background.getWidth(), lb_background.getHeight(),
                            Image.SCALE_SMOOTH);
                    lb_background.setIcon(new ImageIcon(scaledInstance));
        } catch (Exception e) {
        e.printStackTrace();
        }
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pf_oldpassword = new javax.swing.JPasswordField();
        pf_newpassword = new javax.swing.JPasswordField();
        pf_confirmpassword = new javax.swing.JPasswordField();
        bt_changepassword = new javax.swing.JButton();
        lb_background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("old password");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 23, 110, 29);

        jLabel2.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("new password");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 80, 120, 30);

        jLabel3.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("confirm password");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 140, 140, 30);
        getContentPane().add(pf_oldpassword);
        pf_oldpassword.setBounds(170, 20, 200, 30);
        getContentPane().add(pf_newpassword);
        pf_newpassword.setBounds(170, 80, 200, 30);
        getContentPane().add(pf_confirmpassword);
        pf_confirmpassword.setBounds(170, 140, 200, 30);

        bt_changepassword.setBackground(new java.awt.Color(0, 0, 0));
        bt_changepassword.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        bt_changepassword.setForeground(new java.awt.Color(255, 255, 255));
        bt_changepassword.setText("CHANGE");
        bt_changepassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_changepasswordActionPerformed(evt);
            }
        });
        getContentPane().add(bt_changepassword);
        bt_changepassword.setBounds(170, 210, 140, 50);

        lb_background.setText("jLabel4");
        getContentPane().add(lb_background);
        lb_background.setBounds(0, -6, 500, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_changepasswordActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_bt_changepasswordActionPerformed
    {//GEN-HEADEREND:event_bt_changepasswordActionPerformed
        String oldpass=pf_oldpassword.getText();
        String newpass=pf_newpassword.getText();
        String confirmpass=pf_confirmpassword.getText();
        
        if(oldpass.isEmpty()||newpass.isEmpty()||confirmpass.isEmpty())
          {
              JOptionPane.showMessageDialog(this, "Please provide required details");
          }
        else if(!newpass.equals(confirmpass))
          {
            JOptionPane.showMessageDialog(this, "The passwords do not match");
          }
        else
          {
             try
        {
           Class.forName("com.mysql.jdbc.Driver");
            System.out.println("Driver Loading done");
            
            Connection conn = DriverManager.getConnection
        ("jdbc:mysql://127.0.0.1:3306/parkingbookingsystem", "root", "system");
            System.out.println("Connection Created");
            
            Statement stmt = conn.createStatement
        (ResultSet.TYPE_SCROLL_SENSITIVE,
                ResultSet.CONCUR_UPDATABLE);
            System.out.println("Statement Created");
            
            ResultSet rs = stmt.executeQuery("select * from Admin where email='"+email+"' and password='"+oldpass+"'");
            System.out.println("ResultSet Created\n\n");
            if(rs.next())
              {
                rs.updateString("password", newpass);
                rs.updateRow();
                JOptionPane.showMessageDialog(this, "Password Changed Successfully");
                pf_oldpassword.setText("");
                pf_newpassword.setText("");
                pf_confirmpassword.setText("");
              }
            else
              {
                JOptionPane.showMessageDialog(this,"old password is not correct");
              }

        } catch (Exception e)
        {
          e.printStackTrace();
        }
          }
        
    }//GEN-LAST:event_bt_changepasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
          {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
              {
                if ("Nimbus".equals(info.getName()))
                  {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                  }
              }
          } catch (ClassNotFoundException ex)
          {
            java.util.logging.Logger.getLogger(Admin_Change_Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (InstantiationException ex)
          {
            java.util.logging.Logger.getLogger(Admin_Change_Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (IllegalAccessException ex)
          {
            java.util.logging.Logger.getLogger(Admin_Change_Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (javax.swing.UnsupportedLookAndFeelException ex)
          {
            java.util.logging.Logger.getLogger(Admin_Change_Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
               // new Admin_Change_Password("a").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_changepassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lb_background;
    private javax.swing.JPasswordField pf_confirmpassword;
    private javax.swing.JPasswordField pf_newpassword;
    private javax.swing.JPasswordField pf_oldpassword;
    // End of variables declaration//GEN-END:variables
}
